# yaml-language-server: $schema=https://raw.githubusercontent.com/fern-api/fern/main/fern.schema.json

imports:
  root: ../__package__.yml

service:
  auth: false
  base-path: ""
  endpoints:
    create:
      path: /thermostats/climate_setting_schedules/create
      method: POST
      auth: true
      display-name: /thermostats/climate_setting_schedules/create
      request:
        name: ClimateSettingSchedulesCreateRequest
        body:
          properties:
            schedule_type:
              type: optional<literal<"time_bound">>
            device_id: string
            name:
              type: optional<string>
            schedule_starts_at: string
            schedule_ends_at: string
            automatic_heating_enabled:
              type: optional<boolean>
            automatic_cooling_enabled:
              type: optional<boolean>
            hvac_mode_setting:
              type: >-
                optional<root.ClimateSettingSchedulesCreateRequestHvacModeSetting>
            cooling_set_point_celsius:
              type: optional<double>
            heating_set_point_celsius:
              type: optional<double>
            cooling_set_point_fahrenheit:
              type: optional<double>
            heating_set_point_fahrenheit:
              type: optional<double>
            manual_override_allowed:
              type: optional<boolean>
      response:
        docs: OK
        type: root.ClimateSettingSchedulesCreateResponse
      errors:
        - root.BadRequestError
        - root.UnauthorizedError

    delete:
      path: /thermostats/climate_setting_schedules/delete
      method: POST
      auth: true
      display-name: /thermostats/climate_setting_schedules/delete
      request:
        name: ClimateSettingSchedulesDeleteRequest
        body:
          properties:
            climate_setting_schedule_id: string
      response:
        docs: OK
        type: root.ClimateSettingSchedulesDeleteResponse
      errors:
        - root.BadRequestError
        - root.UnauthorizedError

    get:
      path: /thermostats/climate_setting_schedules/get
      method: POST
      auth: true
      display-name: /thermostats/climate_setting_schedules/get
      request:
        name: ClimateSettingSchedulesGetRequest
        body:
          properties:
            climate_setting_schedule_id:
              type: optional<string>
            device_id:
              type: optional<string>
      response:
        docs: OK
        type: root.ClimateSettingSchedulesGetResponse
      errors:
        - root.BadRequestError
        - root.UnauthorizedError

    list:
      path: /thermostats/climate_setting_schedules/list
      method: POST
      auth: true
      display-name: /thermostats/climate_setting_schedules/list
      request:
        name: ClimateSettingSchedulesListRequest
        body:
          properties:
            device_id: string
      response:
        docs: OK
        type: root.ClimateSettingSchedulesListResponse
      errors:
        - root.BadRequestError
        - root.UnauthorizedError

    update:
      path: /thermostats/climate_setting_schedules/update
      method: POST
      auth: true
      display-name: /thermostats/climate_setting_schedules/update
      request:
        name: ClimateSettingSchedulesUpdateRequest
        body:
          properties:
            climate_setting_schedule_id: string
            schedule_type:
              type: optional<literal<"time_bound">>
            name:
              type: optional<string>
            schedule_starts_at:
              type: optional<string>
            schedule_ends_at:
              type: optional<string>
            automatic_heating_enabled:
              type: optional<boolean>
            automatic_cooling_enabled:
              type: optional<boolean>
            hvac_mode_setting:
              type: >-
                optional<root.ClimateSettingSchedulesUpdateRequestHvacModeSetting>
            cooling_set_point_celsius:
              type: optional<double>
            heating_set_point_celsius:
              type: optional<double>
            cooling_set_point_fahrenheit:
              type: optional<double>
            heating_set_point_fahrenheit:
              type: optional<double>
            manual_override_allowed:
              type: optional<boolean>
      response:
        docs: OK
        type: root.ClimateSettingSchedulesUpdateResponse
      errors:
        - root.BadRequestError
        - root.UnauthorizedError
